// apps.js - 全アプリ設定・選択肢定義

const APP_CONFIG = {
  841: {
    name: "職遂 / Work",
    icon: "⚙️",
    employeeId: "Lookup",
    subtable: "Table",
    numberField: "Number_0",
    dateField: "Date",
    topicField: "T",
    explainField: "Text_area_0",
    evidenceField: "Attachment_7",
    topicLabel: "職遂 / Work",
    options: [
      "粗利予算着地見込みの更新 (20 P)",
      "施策導入管理表の更新 (20 P)",
      "顧客ヒアリングの実施（フロント）(20 P)",
      "改善提案の検討・策定（フロント）(20 P)",
      "提案書作成（フロント）(50 P)",
      "メインスピーカーとして新規プレゼンの実施（フロント）(50 P)",
      "メインスピーカー定例会報告の実施（フロント）(30 P)",
      "顧客からの問い合わせ対応（フロント）(20 P)",
      "データ収集・処理またはその自動化の設定の実施（データソリューション）(20 P)",
      "データ分析の実施（データソリューション）(20 P)",
      "週次レポート作成（データソリューション）(30 P)",
      "週次レポートの内容チェックの実施（データソリューション）(20 P)",
      "月次レポート作成（データソリューション）(50 P)",
      "月次レポート内容のチェックの実施（データソリューション）(20 P)",
      "要件ヒアリングの実施（サイト/画像/動画/ブログ）(20 P)",
      "情報設計の実施（サイト/画像/動画/ブログ）(20 P)",
      "ワイヤフレーム作成（サイト/画像/動画/）(20 P)",
      "デザイン制作（サイト/画像/動画）(50 P)",
      "動画制作（動画）(50 P)",
      "記事制作（ブログ）(50 P)",
      "コーディングの実施（サイト）(50 P)",
      "動作確認の実施（サイト/画像/動画/ブログ/広告）(20 P)",
      "進捗管理の実施（サイト/画像/動画/ブログ/広告）(50 P)",
      "スケジュール通りの納品・公開（サイト/画像/動画/ブログ/広告）(50 P)",
      "広告の制作・入稿（バナー・動画・テキスト）（広告運用）(20 P)",
      "広告の入札・予算設定（広告運用）(20 P)",
      "広告運用ツールの設定（広告運用）(10 P)",
      "訪問の同席（広告運用）(10 P)",
      "広告運用における検証作業（依頼分）（広告運用）(20 P)",
      "請求書申請対応 (10 P)",
      "担当外店舗への訪問同行/店舗 (20 P)",
      "PTコンサルとの事前打ち合わせ/店舗 (30 P)",
      "加盟店向け請求の締め作業 (20 P)",
      "要件ヒアリングの実施 (20 P)",
      "デザイン修正（警備なパーツ・バナー・テキストレベル）(20 P)",
      "見積作成 (50 P)",
      "制作素材収集 (30 P)",
      "情報設計の実施 (20 P)",
      "コーディングの実施 (50 P)",
      "動作確認の実施 (20 P)",
      "進捗管理の実施 (50 P)",
      "スケジュール通りの納品・公開 (50 P)",
      "加盟店訪問（直接）(50 P)",
      "加盟店訪問（オンライン）(20 P)",
      "データ分析・競合分析の実施（集客）(20 P)",
      "改善施策の提案（集客）(30 P)",
      "改善施策の採用（集客）(50 P)",
      "改善施策の実行（集客）(50 P)",
      "制作ディレクションの実施（集客）(20 P)",
      "広告代理店ディレクションの実施（集客）(20 P)",
      "動画クリエイティブ新規企画書作成 (50 P)",
      "動画クリエイティブシナリオ・構成案作成 (30 P)",
      "動画クリエイティブ　編集（YouTube・広告・SNSなど）(30 P)",
      "YouTube・SNS関連の数値分析レポート作成、成果報告 (50 P)",
      "WEBサイト　新規制作・リニューアル企画書作成 (50 P)",
      "WEBサイト　ワイヤーフレーム制作 (30 P)",
      "WEBサイト　デザイン制作 (30 P)",
      "WEBメディア、メルマガ　記事新規作成 (20 P)",
      "LINE、メルマガの投稿による成果報告 (50 P)",
      "GA4によるWEBサイトの数値分析レポート作成・報告 (50 P)",
      "新製品パンフ、ラベル企画書・原稿作成 (50 P)",
      "新製品パンフ、ラベルデザイン作成 (30 P)",
      "目標に基づくパンフ・チラシ・販促ツールの新規ディレクション (30 P)",
      "目標に基づくパンフ・チラシ・販促ツールの新規デザイン制作 (30 P)",
      "目標達成に向けた活動達成に向けたチーム内ブレストの実施 (20 P)",
      "成功事例の部内への共有提出 (500 P)",
      "その他 / Other（1 P）"
    ]
  },
  821: {
    name: "目標 / KPI",
    icon: "🎯",
    employeeId: "Lookup_0",
    subtable: "Table",
    numberField: "Number",
    dateField: "Date_0",
    topicField: "L",
    explainField: "Text_area_9",
    evidenceField: "Attachment_9",
    topicLabel: "レベル / Level",
    options: [] // ドロップダウン選択肢は動的取得
  },
  989: {
    name: "AI / Intelli",
    icon: "🤖",
    employeeId: "Lookup_1",
    subtable: "Table",
    numberField: "Number",
    dateField: "Date",
    topicField: "T",
    explainField: "Text_area_1",
    evidenceField: "Attachment_1",
    topicLabel: "項目 / Title",
    options: []
  },
  1068: {
    name: "改善 / Kaizen",
    icon: "💡",
    employeeId: "Lookup_0",
    subtable: "Table",
    numberField: "Number_0",
    dateField: "Date",
    topicField: "T",
    explainField: "Text_area_0",
    evidenceField: "Attachment_7",
    topicLabel: "項目 / Title",
    options: []
  },
  826: {
    name: "教育 / Training",
    icon: "📚",
    employeeId: "Lookup_0",
    subtable: "Table",
    numberField: "Number_0",
    dateField: "Date",
    topicField: "T",
    explainField: "Text_area_0",
    evidenceField: "Attachment_7",
    topicLabel: "教育 / Training",
    options: []
  },
  827: {
    name: "協力 / Teamwork",
    icon: "🤝",
    employeeId: "Lookup_0",
    subtable: "Table",
    numberField: "Number_0",
    dateField: "Date",
    topicField: "T",
    explainField: "Text_area_0",
    evidenceField: "Attachment_8",
    topicLabel: "トピック / TOPIC",
    options: []
  },
  593: {
    name: "感謝 / Thanks",
    icon: "💙",
    employeeId: "Lookup_0",
    subtable: "Table",
    numberField: null, // 番号フィールドなし
    dateField: "Date",
    topicField: "Tilte",
    explainField: "Text_area_0",
    evidenceField: "Attachment_7",
    topicLabel: "項目 / Title",
    options: []
  },
  828: {
    name: "環境 / 5S",
    icon: "🗑️",
    employeeId: "Lookup_1",
    subtable: "Table",
    numberField: "Number_0",
    dateField: "Date",
    topicField: "S",
    explainField: "Text_area_0",
    evidenceField: "Attachment_7",
    topicLabel: "環境 / 5S",
    options: []
  },
  829: {
    name: "方針 / Policy",
    icon: "📋",
    employeeId: "Lookup_1",
    subtable: "Table",
    numberField: "Number_0",
    dateField: "Date",
    topicField: "P",
    explainField: "Text_area_0",
    evidenceField: "Attachment_7",
    topicLabel: "方針 / Policy",
    options: []
  }
};
